language: c
install: wget https://raw.githubusercontent.com/samoht/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.01 TESTS=false INSTALL=false
  - OCAML_VERSION=4.02 TESTS=false INSTALL=false
